apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dex-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dex-user
subjects:
- kind: User
  name: john
